#!/bin/bash                                                                                                                                                                                                                                                         
echo "#Rad   Energy" > radius.log                                                                                                                                                                                                                                   
list="54 55 56 57 58 59 60 61 62"                                                                                                                                                                                                                                      
export OCT_PARSE_ENV=1                                                                                                                                                                                                                                              
for Radius in $list                                                                                                                                                                                                                                                 
do                                                                                                                                                                                                                                                                  
    export OCT_Radius=$(echo $Radius*1.8897261328856432 | bc)                                                                                                                                                                                                       
    octopus >& out-$Radius                                                                                                                                                                                                                                         
    energy=`grep Total static/info  | head -1 | cut -d "=" -f 2`                                                                                                                                                                                                    
    echo $Radius $energy >> radius.log                                                                                                                                                                                                                              
    rm -rf restart                                                                                                                                                                                                                                                  
done                                                                                                                                                                                                                                                                
unset OCT_Radius